services:
  aluguelfacil-db:
    image: postgres:17-alpine
    container_name: aluguelfacil-db
    volumes:
      - postgres_sql:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${ALGUEL_POSTGRES_DB}
      - POSTGRES_USER=${ALGUEL_POSTGRES_USER}
      - POSTGRES_PASSWORD=${ALGUEL_POSTGRES_PASSWORD}
    networks:
      - aluguelfacil-backend
    security_opt:
      - no-new-privileges:true

  aluguelfacil-web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    container_name: aluguelfacil-web
    volumes:
      - ./src:/app
    ports:
      - "127.0.0.1:8015:8000"
    environment:
      - POSTGRES_NAME=${ALGUEL_POSTGRES_DB}
      - POSTGRES_USER=${ALGUEL_POSTGRES_USER}
      - POSTGRES_PASSWORD=${ALGUEL_POSTGRES_PASSWORD}
    depends_on:
      - aluguelfacil-db
    networks:
      #      - caddy
      - aluguelfacil-backend
    #      - monitoring
    security_opt:
      - no-new-privileges:true

volumes:
  postgres_sql:

networks:
  #  caddy:
  #    external: true
  aluguelfacil-backend:
#    external: true
#  monitoring:
#    external: true
