# Generated by Django 6.0.6 on 2026-06-28 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Número com DDD, ex: 5511999999999', max_length=20),
        ),
    ]
