# Generated by Django 6.0.6 on 2026-06-28 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='foto_url',
            field=models.URLField(blank=True, help_text='Link para foto do imóvel'),
        ),
    ]
